project_name: "Holgersync"
before:
  hooks:
    - go mod tidy
builds:
  - id: "holgersync"
    main: ./cmd
    binary: holgersync
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    no_unique_dist_dir: true

release:
  draft: true
  mode: replace
  header: |
    ## Holgersync release