---
name: Linting Code Base

on:
  push:
    tags:
      - v*
    branches:
      - main
      - dev
  pull_request:

jobs:

  golangci:
    name: lint
    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-go@v3
    - uses: actions/checkout@v3

    - uses: golangci/golangci-lint-action@v3
      name: golangci-lint
      with:
        args: --config .golangci.yml